lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/config/routes.rb
Rails.application.routes.draw do
  root 'authors#index'

  resources :authors do
    resources :books
  end

end

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books
end

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :author
end

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
    @books = @author.books
  end

  def new
    @author = Author.new
  end

  def create
    author_params = params.require(:author).permit(:name)
    @author = Author.create(author_params)
    redirect_to @author
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    author_params = params.require(:author).permit(:id, :name)
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to @author
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to authors_path, Notice: "The author was successfully destroyed."
  end
end

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_author
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    # Shows all books by a particular author, and thanks to our "before action", we should already have @author
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    book_params = params.require(:book).permit(:title)
    book = Book.create(book_params)
    @author.books << book # Associate the new book with the correct author
    # We could also associate in 1 step by saying: book = @author.books.create(book_params)
    redirect_to [@author, book]
  end

  def edit
  end

  def update
    book_params = params.require(:book).permit(:title)
    @book.update(book_params)
    redirect_to [@author, @book]
  end

  def destroy
    @book.destroy
    redirect_to author_books_path, Notice: "The book was successfully destroyed."
  end

  private
  def set_author
    @author = Author.find(params[:author_id])
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/helpers/application_helper.rb
module ApplicationHelper
end

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/helpers/authors_helper.rb
module AuthorsHelper
end

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/helpers/books_helper.rb
module BooksHelper
end

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/authors/edit.html.erb
<h1>Authors#edit</h1>

<h2>Please edit this author:</h2>

<%= form_for @author do |f|  %> 
<p><%= f.text_field :name %> </p>
<p><%= f.submit  %> </p>
<% end  %> 

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/authors/index.html.erb
<h1>Authors#index</h1>

<% @authors.each do |a|  %>

<p>Name: <%= a.name %> <%= link_to "Show author", a %>  <p>

<% end  %> 

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/authors/new.html.erb
<h1>Authors#new</h1>

<%= form_for @author do |f|  %> 
<p><%= f.text_field :name %> </p>
<p><%= f.submit  %> </p>
<% end  %> 

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/authors/show.html.erb
<h1>Authors#show</h1>


<h3>The author is:</h3>
<p>
<%= link_to @author.name, author_books_path(@author)  %> - <%= link_to "Add Book", new_author_book_path(@author)  %> 
</p>
<p><%= link_to "Edit Author", edit_author_path %> </p>
<p><%= button_to "Delete Author", @author, :method => :delete  %> 	</p>

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/books/edit.html.erb
<h1>Books#edit</h1>


<h3>Edit this book by <%= @author.name  %> </h3>

<%= form_for [@author, @book] do |f| %> 
<p><%= f.text_field :title  %> </p>
<p><%= f.submit  %> </p>


<% end  %> 

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/books/index.html.erb
<h1>Books#index</h1>

<p>
<%= link_to "Back to Authors", authors_path   %> 
</p>

<h3>All books for <%= @author.name  %> </h3>
<ul>
	
<% @author.books.each do |book|  %> 
<li>Title: <%= book.title  %> <%= link_to("Show Book", [@author, book]) %></li>
<% end %> 
</ul>

<p>
<%= link_to "Add Book", new_author_book_path %> 
</p>

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/books/new.html.erb
<h1>Books#new</h1>

<h3>Make a new book by <%= @author.name  %> </h3>

<%= form_for [@author, @book] do |f| %> 
<p><%= f.text_field :title  %> </p>
<p><%= f.submit  %> </p>


<% end  %> 

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/books/show.html.erb
<h1>Books#show</h1>

<p>
<%= link_to "Back", author_books_path  %> 
</p>

<h3>Book details:</h3>
<p>Title: <%= @book.title %> </p>
<p><%= link_to "Edit Author's Book", edit_author_book_path(@author, @book) %> </p>
<p><%= button_to "Delete Author's Book", [@author, @book], :method => :delete  %> </p>

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

lectures/week-07/_3_wednesday/dawn/prepped/authors_books_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nested Resources Example - Authors and Books App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>